# This is the corrected config for combo mode
http_listen_addr: :6063
introspection_addr: :6060
log_level: error

indexer:
  connstring: "postgresql://clair:clairpassword@postgres:5432/clair6000?sslmode=disable"
  migrations: true

matcher:
  connstring: "postgresql://clair:clairpassword@postgres:5432/clair6000?sslmode=disable"
  migrations: true

notifier:
  connstring: "postgresql://clair:clairpassword@postgres:5432/clair6000?sslmode=disable"
  migrations: true